---
- name: 'Install unclutter command'
  apt: name=unclutter state=present

- name: 'Install x11vnc'
  apt: name=x11vnc state=present

- name: 'Ensure autostart directory exists'
  file:
    path: "/home/pi/.config/autostart"
    state: directory
    recurse: yes
    owner: pi
    group: pi

- name: 'Configure VNC'
  template: src=templates/x11vnc.desktop dest=/home/pi/.config/autostart/x11vnc.desktop owner=pi group=pi mode=0755

- name: 'Disable screen sleep'
  template: src=templates/lightdm.conf dest=/etc/lightdm/lightdm.conf owner=root group=root mode=0644

- name: 'Setup LXDE autostart file'
  template: src=templates/autostart dest=/home/pi/.config/lxsession/LXDE-pi/autostart owner=pi group=pi mode=0644

- name: 'Reboot'
  command: /sbin/reboot
